#!/bin/bash

function repo {
	if [ -d "$1" ]; then
		(cd "$1" && git pull)
	else
		git clone "$2" "$1"
	fi
}

set -e

if [ $# = 0 ]; then
	dest=~
else
	dest="$1"
fi

mkdir -p -- "$dest/.vim/bundle"
cd "$dest/.vim/bundle"

repo bufexplorer https://github.com/jlanzarotta/bufexplorer.git
repo ctrlp.vim https://github.com/kien/ctrlp.vim
repo delimitMate https://github.com/Raimondi/delimitMate.git
repo nerdtree https://github.com/scrooloose/nerdtree
repo supertab https://github.com/ervandew/supertab.git
repo ultisnips https://github.com/SirVer/ultisnips.git
repo vim-fugitive https://github.com/tpope/vim-fugitive.git
repo vim-rooter https://github.com/airblade/vim-rooter.git
repo vim-unimpaired https://github.com/tpope/vim-unimpaired.git
